// Package specs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package specs

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
)

// Defines values for SeatBookingStatus.
const (
	SeatBookingStatusБронируется SeatBookingStatus = "Бронируется"

	SeatBookingStatusЗабранировано SeatBookingStatus = "Забранировано"

	SeatBookingStatusСвободно SeatBookingStatus = "Свободно"
)

// Defines values for SeatPosition.
const (
	SeatPositionПосередине SeatPosition = "Посередине"

	SeatPositionУОкна SeatPosition = "У окна"

	SeatPositionУПрохода SeatPosition = "У прохода"
)

// Defines values for SeatType.
const (
	SeatTypeBuisness SeatType = "Buisness"

	SeatTypeEconomy SeatType = "Economy"
)

// Airport defines model for Airport.
type Airport struct {
	// Город аэропорта.
	City string `json:"city"`

	// Код аэропорта.
	Code string `json:"code"`

	// Страна аэропорта.
	Country string `json:"country"`

	// Описание аэропорта.
	Description *string `json:"description,omitempty"`

	// Идентификатор аэропорта.
	Id string `json:"id"`

	// Название аэропорта.
	Name string `json:"name"`
}

// AirportsList defines model for AirportsList.
type AirportsList []Airport

// Flight defines model for Flight.
type Flight struct {
	// Код рейса.
	Code string `json:"code"`

	// Время вылета.
	From string `json:"from"`

	// Идентификатор аэропорта вылета.
	FromAirportId string `json:"from_airport_id"`

	// Идентификатор рейса.
	Id string `json:"id"`

	// Статус.
	Status string `json:"status"`

	// Время прилёта.
	To string `json:"to"`

	// Идентификатор аэропорта прилёта.
	ToAirportId string `json:"to_airport_id"`
}

// FlightsList defines model for FlightsList.
type FlightsList []Flight

// Seat defines model for Seat.
type Seat struct {
	// Статус бронирования места.
	BookingStatus *SeatBookingStatus `json:"booking_status,omitempty"`

	// Код места.
	Code *string `json:"code,omitempty"`

	// Идентификатор места.
	Id *string `json:"id,omitempty"`

	// Место места.
	Position *SeatPosition `json:"position,omitempty"`

	// Цена места.
	Price *float64 `json:"price,omitempty"`

	// Тип места.
	Type *SeatType `json:"type,omitempty"`
}

// Статус бронирования места.
type SeatBookingStatus string

// Место места.
type SeatPosition string

// Тип места.
type SeatType string

// SeatOption defines model for SeatOption.
type SeatOption struct {
	// Описание услуги для мета.
	Description *string `json:"description,omitempty"`

	// Идентификатор услуги для места.
	Id *string `json:"id,omitempty"`

	// Название услуги для мета.
	Name *string `json:"name,omitempty"`

	// Цена места.
	Price *float64 `json:"price,omitempty"`
}

// SeatOptionsList defines model for SeatOptionsList.
type SeatOptionsList []SeatOption

// SeatsList defines model for SeatsList.
type SeatsList []Seat

// UserProfile defines model for UserProfile.
type UserProfile struct {
	// URL по которому можно получить аватар пользователя.
	AvatarUrl string `json:"avatarUrl"`

	// Идентификатор пользователя.
	Id string `json:"id"`

	// Логин пользователя в системе.
	Login string `json:"login"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v1/airports)
	GetV1Airports(w http.ResponseWriter, r *http.Request)

	// (POST /v1/booking)
	PostV1Booking(w http.ResponseWriter, r *http.Request)

	// (GET /v1/flights)
	FlightsList(w http.ResponseWriter, r *http.Request)

	// (GET /v1/seat_options)
	GetV1SeatOptions(w http.ResponseWriter, r *http.Request)

	// (GET /v1/seats)
	GetV1Seats(w http.ResponseWriter, r *http.Request)

	// (GET /v1/transactions)
	GetV1Transactions(w http.ResponseWriter, r *http.Request)

	// (POST /v1/transactions)
	PostV1Transactions(w http.ResponseWriter, r *http.Request)
	// Информация об аутентифицированном пользователе.
	// (GET /v1/user)
	GetAuthUser(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetV1Airports operation middleware
func (siw *ServerInterfaceWrapper) GetV1Airports(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Airports(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostV1Booking operation middleware
func (siw *ServerInterfaceWrapper) PostV1Booking(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Booking(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// FlightsList operation middleware
func (siw *ServerInterfaceWrapper) FlightsList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FlightsList(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetV1SeatOptions operation middleware
func (siw *ServerInterfaceWrapper) GetV1SeatOptions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1SeatOptions(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetV1Seats operation middleware
func (siw *ServerInterfaceWrapper) GetV1Seats(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Seats(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetV1Transactions operation middleware
func (siw *ServerInterfaceWrapper) GetV1Transactions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Transactions(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostV1Transactions operation middleware
func (siw *ServerInterfaceWrapper) PostV1Transactions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Transactions(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetAuthUser operation middleware
func (siw *ServerInterfaceWrapper) GetAuthUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthUser(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/airports", wrapper.GetV1Airports)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/booking", wrapper.PostV1Booking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/flights", wrapper.FlightsList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/seat_options", wrapper.GetV1SeatOptions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/seats", wrapper.GetV1Seats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/transactions", wrapper.GetV1Transactions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/transactions", wrapper.PostV1Transactions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/user", wrapper.GetAuthUser)
	})

	return r
}
